spring.application.name=sismed-aggregator-service
spring.graphql.graphiql.enabled=true

spring.datasource.url=${AGGREGATOR_DB_URL}
spring.datasource.username=${AGGREGATOR_DB_USER}
spring.datasource.password=${AGGREGATOR_DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.defer-datasource-initialization=true

sismed.jwt.segredo=c2lzbWVkLXNlY3JldC1rZXktcGFyYS1qd3QtYXNzaW5hdHVyYS1obWFjLXNoYTI1Ng==
sismed.jwt.expiracao-ms=28800000

grpc.client.paciente.address=static://sismed-patient-service:6565
grpc.client.paciente.negotiationType=PLAINTEXT

grpc.client.agendamento.address=static://sismed-scheduling-service:7575
grpc.client.agendamento.negotiationType=PLAINTEXT
