spring.application.name=sismed-aggregator-service
spring.graphql.graphiql.enabled=true

spring.datasource.url=jdbc:h2:mem:sismed_auth;DB_CLOSE_DELAY=-1
spring.datasource.driver-class-name=org.h2.Driver
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=false

sismed.jwt.segredo=c2lzbWVkLXNlY3JldC1rZXktcGFyYS1qd3QtYXNzaW5hdHVyYS1obWFjLXNoYTI1Ng==
sismed.jwt.expiracao-ms=28800000

grpc.client.paciente.address=static://localhost:6565
grpc.client.paciente.negotiationType=PLAINTEXT

grpc.client.agendamento.address=static://localhost:7575
grpc.client.agendamento.negotiationType=PLAINTEXT
