spring.application.name=sismed-scheduling-service

grpc.server.port=7575

spring.datasource.url=${SCHEDULING_DB_URL}
spring.datasource.username=${SCHEDULING_DB_USER}
spring.datasource.password=${SCHEDULING_DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always

sismed.scheduling-broker.url=sismed-scheduling-broker:9092
sismed.scheduling-broker.topic=scheduling-notification
