spring.application.name=sismed-patient-service

grpc.server.port=6565

spring.datasource.url=${PATIENT_DB_URL}
spring.datasource.username=${PATIENT_DB_USER}
spring.datasource.password=${PATIENT_DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always
